# Generated by Django 5.2.8 on 2026-01-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_booking_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
