# Generated by Django 5.2.8 on 2026-01-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
