# Generated by Django 5.2.8 on 2026-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_menuitem_description_menuitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for guest bookings', max_length=254, null=True),
        ),
    ]
