# Generated by Django 5.2.8 on 2026-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_booking_guest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for the booking', max_length=254, null=True),
        ),
    ]
